services:
  chromadb:
    image: chromadb/chroma:0.5.20
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=TRUE

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./model_pull.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "entrypoint.sh"]

  rag_agent:
    stdin_open: true
    tty: true
    build:
      context: .
      target: development
    container_name: rag_agent
    depends_on:
      - chromadb
      - ollama
    volumes:
      - .:/app
      - hugs_cache:/root/.cache/hugs

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    container_name: rag_frontend
    ports:
      - "8501:8501"
    depends_on:
      - rag_agent
    volumes:
      - ./frontend:/app/frontend

volumes:
  chroma_data:
  ollama_data:
  hugs_cache:
